version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      node: 10
  build:
    commands:
      - python --version
      - pip install aws-sam-cli
  post_build:
    commands:
      - echo hiii, new version
      - sam deploy

artifacts:
  files:
    - "**/*"
    - appspec.yaml
