version: 0.2

phases:
  install:
    runtime-versions:
      node: 10
  build:
    commands:
      - ls
  post_build:
    commands:
      - echo DevOps-Pipeline-sam-/BuildOutpu/$CODEBUILD_KMS_KEY_ID/appspec.yaml
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_INITIATOR
      - echo $CODEBUILD_BUILD_NUMBER
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_BUILD_ARN
      - echo $CODEBUILD_BATCH_BUILD_IDENTIFIER
      - echo $BUCKET_DEPLOYMENTS
      - export REVISION='{"revisionType":"S3","s3Location":"{"bucket":"$BUCKET_DEPLOYMENTS","key":"codepipeline-work--us-east-1/DevOps-Pipeline-sam-/BuildOutpu/3hqSM09.zip/appspec.yaml","bundleType":"YAML"}"}'
      - aws deploy create-deployment --revision=$REVISION --application-name=$APPLICATION_NAME --deployment-group-name=$DEPLOYMENT_GROUP_NAME --deployment-config-name='CodeDeployDefault.LambdaCanary10Percent30Minutes'

artifacts:
  files:
    - "**/*"
