version: 0.2

phases:
  install:
    runtime-versions:
      node: 10
  build:
    commands:
      - ls
      - echo $DEPLOYMENT_GROUP_NAME
      - echo $BUCKET_DEPLOYMENTS
      - echo $APPLICATION_NAME
  post_build:
    commands: 
      - export REVISION='{"revisionType":"S3","s3Location":{"bucket":"$BUCKET_DEPLOYMENTS","key":"$CODEBUILD_BUILD_ID/appspec.yaml","bundleType":"YAML"}}'
      - echo $REVISION
      - aws deploy create-deployment --revision=$REVISION --application-name=$APPLICATION_NAME --deployment-group-name=$DEPLOYMENT_GROUP_NAME --deployment-config-name='CodeDeployDefault.LambdaCanary10Percent30Minutes'

artifacts:
  files:
    - '**/*'