version: 0.2

phases:
  build:
    commands:
      - python --version
      - echo hiii, new version
      - pip install aws-sam-cli
  post_build:
    commands:
      - echo hiii, new version
      - sam build
      - sam deploy
artifacts:
  files:
    - "**/*"
