version: 0.2

phases:
  install:
    runtime-versions:
      node: 10
  build:
    commands:
      - ls
  post_build:
    commands:
      - echo DevOps-Pipeline-sam-/BuildOutpu/$CODEBUILD_KMS_KEY_ID/appspec.yaml
      - export REVISION='{"revisionType":"S3"}'
      - export S3LOCATION='{"bucket":"$BUCKET_DEPLOYMENTS", "key":"DevOps-Pipeline-sam-/BuildOutpu/$CODEBUILD_KMS_KEY_ID/appspec.yaml", "bundleType":"YAML"}'
      - aws deploy create-deployment --revision=$REVISION --s3-location=$S3LOCATION --application-name=$APPLICATION_NAME --deployment-group-name=$DEPLOYMENT_GROUP_NAME --deployment-config-name='CodeDeployDefault.LambdaCanary10Percent30Minutes'

artifacts:
  files:
    - "**/*"
